import FileDrop from "../hooks/filedrop";
import styles from '../styles/Home.module.css';
import Dropdown from 'react-bootstrap/Dropdown';
import DropdownButton from 'react-bootstrap/DropdownButton';
import Button from 'react-bootstrap/Button'
import Table from 'react-bootstrap/Table';
import { useCallback, useState } from "react";

function Home(props) {
  const [reportNumber, setReportNumber] = useState()
  const [reports, setReports] = useState([])
  const handleChange = useCallback((e) => setReportNumber(e), []);


     const getFromBackend = async (reportNumber) => {
      //TODO Report Number to get specified report
        fetch('http://localhost:3001/report/getReport',{
          method: "POST",
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify( {
              ReportNumber: reportNumber
                    }),
        })
            .then(function(response) {
                return response.json();
            }).then(function(data) {
            setReports(data.employeeReports);  
            });
     }


  return (
    <div className={styles.container}>
      <h1>
        <title className="a">Wave Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </h1>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the Wave 
          <img
              src="wave.png"
              width="30"
              height="30"
              className="d-inline-block align-top"
              alt="Tactable logo"
            />
            assessment
          
        </h1>

        <p className={styles.description}>
          Get started by importing your .csv Time Report
        </p>

        <div className={styles.grid}>
          <FileDrop getNumbers={props.getNumbers}/>
        </div>

        <div className={styles.grid}>
          
          {props.numberReports ? 
          <DropdownButton className={styles.button} id="dropdown-basic-button" title={reportNumber || "Choose Report"} variant="secondary" onSelect={handleChange}>
            {props.numberReports.map( i => 
                <Dropdown.Item key={i.title} eventKey={i.title}>{i.title}</Dropdown.Item>
              )}
          </DropdownButton>
        :
        <div></div>
        }
        <Button className={styles.button} variant="warning"
                    onClick={() => {
                        getFromBackend(reportNumber);
                            }}
                        >
                    Get Report
                 </Button>
        </div>
        <div className={styles.grid}>
          <Table className={styles.table} striped bordered hover variant="dark">
            <thead>
              <tr>
                <th>ID</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Amount Paid</th>
              </tr>
            </thead>
            
              {reports ? 
              <tbody>
              {reports.map( i =>    
                <tr key={i.employee_id}>
                  <td>{i.employee_id}</td>
                  <td>{i.payPeriod.startDate}</td>
                  <td>{i.payPeriod.endDate}</td>
                  <td>{i.amountPaid}</td>
                </tr>
                )}
                </tbody>
                :
                <div></div>
                }
          </Table>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/fons95/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made by Alfonso Diaz Infante
        </a>
      </footer>
    </div>
  );
}

export default Home;
